### ISSUE TITLE
Can you choose licence to this project?

### ISSUE THREAD

**Issue by xlmnxp** [rayed/Quran#2]
I want reuse your project to create other project but I can't because you didn't choose licence to this project

**Comment by rayed** [comment]
Please do, it is mainly data of Quran and Tafseer, and I don't have any copyright on them, and you are most likely going to need to transform these data to different format e.g. sqlite.

**Comment by xlmnxp** [comment]
You can choose MIT or GNU License for this project
I don't want copyrights of the Quran or Tafseer.
I want to obtain a license for this project only

**Comment by rayed** [comment]
The project is mainly content not source code, as far as I know GNU and MIT License are for source code!
